Repository supercoding-commerce/FE, pull requests merged in 2023-09, with the labels that each got.

#15 feat: #8 Select 공통 컴포넌트 구현
  src/assets/icon/ArrowDown.svg
  src/assets/icon/ArrowUp.svg
  src/assets/icon/index.ts
  src/components/common/SelectBox/SelectBox.styles.tsx
  src/components/common/SelectBox/SelectBox.tsx
  src/components/common/commonUiTest/SelectTest.tsx
Labels: ✨ feature

#19 feat : 별점 레이팅 구현
  src/assets/icon/Rate.svg
  src/assets/icon/index.ts
  src/components/Test/Test.tsx
  src/components/common/Icon.tsx
  src/components/common/Rating/Rating.styles.tsx
  src/components/common/Rating/Rating.tsx
  src/components/icons/ClearIcon.tsx
  src/styles/theme.ts
Labels: ✨ feature

#22 Feature/header
  src/components/common/Header/SearchHeader.styles.tsx
  src/components/common/Header/SearchHeader.tsx
  src/pages/Home/Home.tsx
Labels: 🔥 priority:high, ✨ feature

#23 페이지별 Header UI 구현
  src/assets/icon/ArrowLeft.svg
  src/assets/icon/index.ts
  src/components/common/PageHeader/Header.styles.tsx
  src/components/common/PageHeader/Header.tsx
Labels: ✨ feature

#27 feature : Layout 작업 및 URL 별 헤더 작업
  src/App.tsx
  src/components/common/Header/DefaultHeader.styles.tsx
  src/components/common/Header/DefaultHeader.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/SearchHeader.styles.tsx
  src/components/common/Header/SearchHeader.tsx
  src/pages/DefaultLayout/DefaultLayout.styles.tsx
  src/pages/DefaultLayout/DefaultLayout.tsx
  src/pages/routes.tsx
Labels: 🔥 priority:high, ✨ feature

#30 feat: #25 footer UI 구현
  src/components/common/Footer/DefaultFooter.styles.tsx
  src/components/common/Footer/DefaultFooter.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/SignFooter.styles.tsx
  src/components/common/Footer/SignFooter.tsx
  src/pages/DefaultLayout/DefaultLayout.styles.tsx
  src/pages/DefaultLayout/DefaultLayout.tsx
Labels: ✨ feature

#28 feat : MyPage UI 구현
  src/assets/icon/ArrowRight.svg
  src/assets/icon/Box.svg
  src/assets/icon/CreditCard.svg
  src/assets/icon/Database.svg
  src/assets/icon/Heart.svg
  src/assets/icon/Paper.svg
  src/assets/icon/Ticket.svg
  src/assets/icon/index.ts
  src/components/common/Button/Button.styles.tsx
  src/components/common/Button/Button.tsx
  src/pages/MyPage/MyPage.styles.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/routes.tsx
  src/styles/GlobalStyle.tsx
Labels: ✨ feature

#31 Feat : SignInPage UI 구현
  src/assets/icon/SymbolKakao.svg
  src/assets/icon/index.ts
  src/pages/SignInPage/SignInPage.styles.tsx
  src/pages/SignInPage/SignInPage.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#33 Feat : SignUp Page UI 구현
  src/pages/SignUpPage/SignUpPage.styles.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#35 Feature/counter
  src/components/common/Counter/Counter.styles.tsx
  src/components/common/Counter/Counter.tsx
  src/components/common/commonUiTest/CounterTest.tsx
Labels: ✨ feature

#37 Feat : 판매자 / 구매자 회원가입 페이지 UI 구현
  src/App.tsx
  src/components/signup/SignUpForm/SignUpForm.styles.tsx
  src/components/signup/SignUpForm/SignUpForm.tsx
  src/pages/SignUpUserPage/SignUpUserPage.styles.tsx
  src/pages/SignUpUserPage/SignUpUserPage.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#17 feat#16 input component
  src/components/common/Input/Input.styles.tsx
  src/components/common/Input/Input.tsx
  src/styles/theme.ts
Labels: ✨ feature

#42 feat:#14 카테고리 컴포넌트 완료
  src/components/common/Category/Category.styles.tsx
  src/components/common/Category/Category.tsx
  src/components/common/commonUiTest/CategoryTest.tsx
Labels: ✨ feature

#41 fix : vercel 404 에러 해결 파일 추가
  vercel.json
Labels: 🐛 bug

#46 refactor:#44 button 공동컴포넌트 theme 폰트 추가
  src/components/common/Button/Button.styles.tsx
Labels: ♻️ refactor

#48 Feature/chat UI
  src/assets/icon/Add.svg
  src/assets/icon/Airplane.svg
  src/assets/icon/index.ts
  src/components/chat/Chat.styles.tsx
  src/components/chat/Chat.tsx
  src/components/chat/chatDetail/ChatDetailBody.tsx
  src/components/chat/chatDetail/ChatDetailHeader.tsx
  src/components/chat/chatDetail/ChatDetailIntro.tsx
  src/components/chat/chatDetail/ChatLeftBox.tsx
  src/components/chat/chatDetail/ChatRightBox.tsx
  src/components/chat/chatDetail/ChatSend.tsx
  src/components/chat/chatList/ChatBody.tsx
  src/components/chat/chatList/ChatBox.tsx
  src/components/chat/chatList/ChatHeader.tsx
  src/components/common/Category/Category.styles.tsx
  src/components/common/Category/Category.tsx
  src/components/common/commonUiTest/CategoryTest.tsx
  vercel.json
Labels: ✨ feature

#49 feat:#43 chat ui 작업완료
  src/assets/icon/Add.svg
  src/assets/icon/Airplane.svg
  src/assets/icon/index.ts
  src/components/chat/Chat.styles.tsx
  src/components/chat/Chat.tsx
  src/components/chat/chatDetail/ChatDetailBody.tsx
  src/components/chat/chatDetail/ChatDetailHeader.tsx
  src/components/chat/chatDetail/ChatDetailIntro.tsx
  src/components/chat/chatDetail/ChatLeftBox.tsx
  src/components/chat/chatDetail/ChatRightBox.tsx
  src/components/chat/chatDetail/ChatSend.tsx
  src/components/chat/chatList/ChatBody.tsx
  src/components/chat/chatList/ChatBox.tsx
  src/components/chat/chatList/ChatHeader.tsx
Labels: ✨ feature

#47 feat : 로그인 유효성 검사 로직 구현
  src/components/common/Input/Input.styles.tsx
  src/components/common/SelectBox/SelectBox.tsx
  src/hooks/useInputs.ts
  src/pages/SignInPage/SignInPage.tsx
  src/utils/validate.ts
Labels: ✨ feature

#55 feat : textField component
  src/components/common/Input/Input.styles.tsx
  src/components/common/Input/Input.tsx
  src/components/common/TextField/TextField.styles.tsx
  src/components/common/TextField/TextField.tsx
  src/components/common/commonUiTest/TextFieldTest.tsx
Labels: ✨ feature

#57 fix : selectbox 버그 수정
  src/components/common/SelectBox/SelectBox.styles.tsx
Labels: 🐛 bug

#58 feat : #45 CartPage UI
  src/assets/icon/X.svg
  src/assets/icon/index.ts
  src/components/common/Counter/Counter.styles.tsx
  src/components/common/Header/Header.tsx
  src/pages/CartPage/CartItem.styles.tsx
  src/pages/CartPage/CartItem.tsx
  src/pages/CartPage/CartPage.styles.tsx
  src/pages/CartPage/CartPage.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#65 feat : 상품 추가/수정 패이지 UI 작업
  src/assets/icon/Cameta.svg
  src/assets/icon/index.ts
  src/components/ImageUploader/ImageUploader.styles.tsx
  src/components/ImageUploader/ImageUploader.tsx
  src/components/OptionAdder/OptionAdder.styles.tsx
  src/components/OptionAdder/OptionAdder.tsx
  src/components/OptionItem/OptionItem.styles.tsx
  src/components/OptionItem/OptionItem.tsx
  src/components/ProductForm/ProductForm.styles.tsx
  src/components/ProductForm/ProductForm.tsx
  src/components/Test/Test.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Input/Input.styles.tsx
  src/components/common/Radio/Radio.styles.tsx
  src/components/common/Radio/Radio.tsx
  src/components/common/Radio/RadioGroup.tsx
  src/components/common/SelectBox/SelectBox.styles.tsx
  src/components/common/TextField/TextField.styles.tsx
  src/components/common/TextField/TextField.tsx
  src/components/common/Textarea.tsx
  src/components/icons/CheckIcon.tsx
  src/components/icons/ClearIcon.tsx
  src/components/icons/DeleteIcon.tsx
  src/const/index.ts
  src/hooks/useHover.ts
  src/hooks/useInput.ts
  src/hooks/useInputs.ts
  src/models/product.ts
  src/pages/AddProduct/AddProduct.tsx
  src/pages/DefaultLayout/DefaultLayout.styles.tsx
  src/pages/UpdateProduct/UpdateProduct.tsx
  src/pages/routes.tsx
  src/styles/theme.ts
Labels: ✨ feature

#62 feat:#54,#63 소켓 관련 기능 구현
  package.json
  src/components/chat/Chat.tsx
  src/components/chat/chatDetail/ChatSend.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ✨ feature

#53 feat: #52 mainpage ui 작업 및 Category 작업
  package.json
  src/assets/icon/Accessories.svg
  src/assets/icon/Cap.svg
  src/assets/icon/Dress.svg
  src/assets/icon/Gloves.svg
  src/assets/icon/Hood.svg
  src/assets/icon/Jeans.svg
  src/assets/icon/Knit.svg
  src/assets/icon/Leggings.svg
  src/assets/icon/LongDress.svg
  src/assets/icon/Muffler.svg
  src/assets/icon/Pants.svg
  src/assets/icon/Shoes.svg
  src/assets/icon/ShortDress.svg
  src/assets/icon/Shorts.svg
  src/assets/icon/Sleeveless.svg
  src/assets/icon/Sweat.svg
  src/assets/icon/Top.svg
  src/assets/icon/Training.svg
  src/assets/icon/index.ts
  src/components/MainPage/ListItemComponent/AllProductList.styles.tsx
  src/components/MainPage/ListItemComponent/AllProductList.tsx
  src/components/MainPage/ListItemComponent/HotItemList.tsx
  src/components/MainPage/MainPage.styles.tsx
  src/components/MainPage/MainPage.tsx
  src/components/MainPage/Swiper/BannerSwiper.styles.tsx
  src/components/MainPage/Swiper/BannerSwiper.tsx
  src/components/common/Header/CategoryHeader.styles.tsx
  src/components/common/Header/CategoryHeader.tsx
  src/data/swiperimg.js
  src/image/BannerSwiper/image1.png
  src/image/BannerSwiper/image2.jpg
  src/image/BannerSwiper/image3.jpg
  src/image/BannerSwiper/image4.jpg
  src/image/BannerSwiper/image5.jpg
  src/image/BannerSwiper/image6.jpg
  src/pages/Category/Menu.tsx
  src/pages/DefaultLayout/DefaultLayout.tsx
  src/pages/Home/Home.tsx
  src/pages/routes.tsx
  src/recoil/productListState.ts
  src/styles/theme.ts
  tsconfig.json
  yarn.lock
Labels: ✨ feature

#72 feat : axios interceptors 세팅 및 로그인 기능 구현
  .env.example
  .gitignore
  package.json
  src/App.tsx
  src/apis/index.ts
  src/apis/user.ts
  src/constants/index.ts
  src/pages/SignInPage/SignInPage.tsx
  src/recoil/userState.ts
  src/utils/localstorage.ts
  src/utils/parseJwt.ts
  vite.config.ts
Labels: ✨ feature

#67 feature : 주문 페이지 UI 구현
  src/assets/icon/ArrowRightFill.svg
  src/assets/icon/index.ts
  src/pages/DefaultLayout/DefaultLayout.styles.tsx
  src/pages/Payment/Payment.styles.tsx
  src/pages/Payment/Payment.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#87 feat : detailPage UI(제품 정보, 옵션)
  src/assets/icon/EmptyHeart.svg
  src/assets/icon/FullHeart.svg
  src/assets/icon/index.ts
  src/components/DetailFooter/DetailFooter.styles.tsx
  src/components/DetailFooter/DetailFooter.tsx
  src/components/DetailHeader/DetailHeader.styles.tsx
  src/components/DetailHeader/DetailHeader.tsx
  src/components/DetailHeader/ProductOption.styles.tsx
  src/components/DetailHeader/ProductOption.tsx
  src/components/common/Counter/Counter.styles.tsx
  src/components/common/Counter/Counter.tsx
  src/components/common/Header/Header.tsx
  src/pages/DetailPage/DetailPage.styles.tsx
  src/pages/DetailPage/DetailPage.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#74 feat:#69 , #76, #78
  src/components/chat/Chat.styles.tsx
  src/components/chat/Chat.tsx
  src/components/chat/chatDetail/ChatDetailBody.tsx
  src/components/chat/chatDetail/ChatDetailHeader.tsx
  src/components/chat/chatDetail/ChatDetailIntro.tsx
  src/components/chat/chatDetail/ChatLeaveBox.tsx
  src/components/chat/chatDetail/ChatLeftBox.tsx
  src/components/chat/chatDetail/ChatRightBox.tsx
  src/components/chat/chatDetail/ChatSend.tsx
  vite.config.ts
Labels: ✨ feature

#81 feat:#80 chat 목록리스트 axios로 받은 후 데이터 뿌리기 완료
  src/components/chat/Chat.styles.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatDetail.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/chatDetail/ChatDetailBody.tsx
  src/components/chat/chatList/ChatBody.tsx
  src/components/chat/chatList/ChatBox.tsx
  src/components/chat/chatList/ChatHeader.tsx
Labels: ✨ feature

#84 feat : header 로그인기능 구현
  src/components/common/Header/SearchHeader.tsx
Labels: ✨ feature

#88 feat:#80 chat 목록리스트 axios로 받은 후 데이터 뿌리기 완료
  src/components/chat/Chat.styles.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatDetail.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/chatDetail/ChatDetailBody.tsx
  src/components/chat/chatList/ChatBody.tsx
  src/components/chat/chatList/ChatBox.tsx
  src/components/chat/chatList/ChatHeader.tsx
Labels: ✨ feature

#91 feat:#90 chatList에서 chatbox클릭하면 해당 채팅창으로 넘어가기 완료
  src/components/chat/Chat.tsx
  src/components/chat/ChatDetail.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/chatDetail/ChatDetailHeader.tsx
  src/components/chat/chatList/ChatBody.tsx
  src/components/common/Header/SearchHeader.tsx
Labels: ✨ feature

#96 feat:#93 chat 채팅창 x버튼 추가완료
  src/components/chat/Chat.styles.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatDetail.tsx
  src/components/chat/chatDetail/ChatDetailHeader.tsx
  src/main.tsx
Labels: ✨ feature

#99 feat : 상품 추가 기능 구현
  package.json
  src/apis/index.ts
  src/apis/product.ts
  src/components/ProductForm/ProductForm.tsx
  src/main.tsx
  src/pages/DefaultLayout/DefaultLayout.styles.tsx
  src/queries/product/mutation.ts
  src/queries/queryKeys.ts
  yarn.lock
Labels: ✨ feature

#92 feat:#90chatList에서 chatbox클릭하면 해당 채팅창이동, #93 채팅방 x버튼 추가
  src/assets/icon/Chat.svg
  src/assets/icon/index.ts
  src/components/chat/Chat.styles.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatButton.tsx
  src/components/chat/ChatDetail.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/chatDetail/ChatDetailHeader.tsx
  src/components/chat/chatList/ChatBody.tsx
  src/components/common/Button/Button.styles.tsx
Labels: ✨ feature

#109 feat: mainpage 라우팅, 스크를바, 스와이퍼스타일링 완료
  src/components/FilterModal/FilterModal.styles.tsx
  src/components/FilterModal/FilterModal.tsx
  src/components/MainPage/ListItemComponent/AllProductList.tsx
  src/components/MainPage/ListItemComponent/ListItem.tsx
  src/components/MainPage/MainPage.styles.tsx
  src/components/MainPage/Swiper/BannerSwiper.styles.tsx
  src/components/MainPage/Swiper/BannerSwiper.tsx
  src/pages/ProductPage/CategoryList.tsx
  src/pages/ProductPage/ProductPage.styles.tsx
  src/pages/ProductPage/ProductPage.tsx
Labels: ✨ feature

#113 Refactor : 토큰 처리 부분 로직 수정
  src/apis/index.ts
  src/constants/index.ts
  src/pages/SignInPage/SignInPage.tsx
Labels: ♻️ refactor

#95 feat : 회원가입 기능 구현
  package.json
  src/apis/user.ts
  src/components/common/AddressModal/AddressModal.styles.tsx
  src/components/common/AddressModal/AddressModal.tsx
  src/components/signup/SignUpForm/SignUpForm.styles.tsx
  src/components/signup/SignUpForm/SignUpForm.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpUserPage/SignUpUserPage.styles.tsx
  src/utils/validate.ts
  yarn.lock
Labels: ✨ feature

#131 feat : Cart API 연결
  src/apis/cart.ts
  src/pages/CartPage/CartItem.styles.tsx
  src/pages/CartPage/CartItem.tsx
  src/pages/CartPage/CartPage.styles.tsx
  src/pages/CartPage/CartPage.tsx
Labels: ✨ feature

#125 Feature/mainpage
  src/components/MainPage/ListItemComponent/AllProductList.tsx
  src/pages/Category/Menu.tsx
Labels: ✨ feature

#122 Feature/category productpage
  src/apis/categoryProduct.ts
  src/components/FilterModal/FilterModal.styles.tsx
  src/components/FilterModal/FilterModal.tsx
  src/components/MainPage/ListItemComponent/HotItemList.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/DefaultHeader.tsx
  src/pages/ProductPage/CategoryList.tsx
  src/pages/ProductPage/ProductPage.styles.tsx
  src/pages/ProductPage/ProductPage.tsx
Labels: ✨ feature, ♻️ refactor

#133 feat:chat detailPage에 채팅 버튼 추가 완료
  src/App.tsx
  src/components/chat/Chat.styles.tsx
  src/components/chat/ChatButton.tsx
  src/pages/DetailPage/DetailPage.tsx
Labels: ✨ feature

#138 feat : 로그아웃 기능 구현
  src/assets/icon/SignOut.svg
  src/assets/icon/index.ts
  src/pages/MyPage/MyPage.tsx
Labels: ✨ feature

#139 feat : Protected 컴포넌트 개발 및 라우팅별 권한 적용
  package.json
  src/components/Test/Test.tsx
  src/components/common/Header/SearchHeader.tsx
  src/pages/AddProduct/AddProduct.tsx
  src/pages/DefaultLayout/DefaultLayout.tsx
  src/pages/ProtectedRoute.tsx
  src/pages/routes.tsx
  yarn.lock
Labels: ✨ feature, ♻️ refactor

#140 fix : 잘못된 프로덕트 상세 페이지 라우팅 url 변경
  src/pages/routes.tsx
Labels: 🐛 bug

#142 fix: 상대방이 보낸 채팅 실시간 반영 안되는 이슈 완료
  src/components/Detail/detailInformation/InformationBox.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatDetail.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/chatDetail/ChatDetailHeader.tsx
  src/components/chat/chatList/ChatBody.tsx
  src/pages/DetailPage/DetailPage.tsx
Labels: 🐛 bug, ✨ feature

#143 feat : 상품 결제 하기 기능 구현
  src/apis/coupon.ts
  src/apis/order.ts
  src/apis/payment.ts
  src/apis/user.ts
  src/components/CouponItem/CouponItem.styles.tsx
  src/components/CouponItem/CouponItem.tsx
  src/components/DetailFooter/DetailFooter.tsx
  src/components/common/Button/Button.styles.tsx
  src/components/common/Icon.tsx
  src/components/common/Modal/Modal.styles.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/ModalContent.tsx
  src/components/common/Modal/ModalHeader.tsx
  src/components/common/Portal.tsx
  src/components/modals/CouponModal.tsx
  src/hooks/useToggle.ts
  src/main.tsx
  src/models/coupon.ts
  src/models/order.ts
  src/pages/DefaultLayout/DefaultLayout.tsx
  src/pages/Payment/Payment.styles.tsx
  src/pages/Payment/Payment.tsx
  src/queries/coupon/query.ts
  src/queries/order/query.ts
  src/queries/payments/mutation.ts
  src/queries/queryKeys.ts
  src/queries/user/query.ts
Labels: ✨ feature

#136 feat: searchpage UI 및 기능구현
  package.json
  src/components/common/Header/Header.tsx
  src/pages/Search/Search.styles.tsx
  src/pages/Search/Search.tsx
  src/pages/routes.tsx
  yarn.lock
Labels: ✨ feature

#153 feat:채팅 입력창 form으로 변경 완료
  src/assets/icon/Smile.svg
  src/assets/icon/index.ts
  src/components/chat/Chat.styles.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatDetail.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/chatDetail/ChatDetailBody.tsx
  src/components/chat/chatDetail/ChatLeftBox.tsx
  src/components/chat/chatDetail/ChatSend.tsx
  src/components/chat/chatList/ChatHeader.tsx
  src/pages/DetailPage/DetailPage.tsx
Labels: ✨ feature

#151 feat:채팅 css 수정[아직 한가지 남음 리뷰x]
  src/assets/icon/Smile.svg
  src/assets/icon/index.ts
  src/components/chat/Chat.styles.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatDetail.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/chatDetail/ChatDetailBody.tsx
  src/components/chat/chatDetail/ChatLeftBox.tsx
  src/components/chat/chatList/ChatHeader.tsx
  src/pages/DetailPage/DetailPage.tsx
Labels: ✨ feature

#159 fix:#154 채팅 판매자 랜덤으로 실시간반영 이슈
  src/components/chat/ChatDetail.tsx
  src/components/chat/chatList/ChatBody.tsx
Labels: 🐛 bug

#149 feat : mypage 구매이력
  src/apis/mypage.ts
  src/components/Mypage-Purchase/Purchase.styles.tsx
  src/components/Mypage-Purchase/Purchase.tsx
  src/components/common/Header/Header.tsx
  src/pages/routes.tsx
  src/styles/theme.ts
Labels: ✨ feature

#158 feat: searchProduct파일 생성 및 라우팅 재설정
  src/components/common/Header/Header.tsx
  src/pages/Search/SearchProduct.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#157 feat: 키워드별 api통신로직 변경 ProductPage props부분 수정
  src/apis/categoryProduct.ts
  src/pages/Category/Menu.tsx
  src/pages/ProductPage/CategoryList.tsx
  src/pages/ProductPage/ProductPage.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#162 feat : 판매내역
  src/apis/mypage.ts
  src/components/Mypage-Sold/SoldPage.styles.tsx
  src/components/Mypage-Sold/SoldPage.tsx
  src/components/common/Header/Header.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#166 feat: mainpage header에 검색아이콘 클릭시 라우팅 추가
  src/components/common/Header/SearchHeader.tsx
Labels: ✨ feature

#167 feat : cartPage 수정
  src/pages/CartPage/CartItem.styles.tsx
  src/pages/CartPage/CartPage.styles.tsx
  src/pages/CartPage/CartPage.tsx
Labels: ✨ feature

#168 feat:#144 채팅방 판매자 이미지 반영하기
  src/components/chat/Chat.tsx
  src/components/chat/ChatDetail.tsx
  src/components/chat/chatDetail/ChatDetailBody.tsx
  src/components/chat/chatDetail/ChatDetailIntro.tsx
  src/components/chat/chatDetail/ChatLeftBox.tsx
  src/pages/DetailPage/DetailPage.tsx
Labels: ✨ feature

#172 feat : paymoney UI
  src/assets/icon/Card1.svg
  src/assets/icon/Card2.svg
  src/assets/icon/Card3.svg
  src/assets/icon/PCoin.svg
  src/assets/icon/index.ts
  src/components/common/Header/Header.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/PayMoney/CardSwiper/CardSwiper.styles.tsx
  src/pages/PayMoney/CardSwiper/CardSwiper.tsx
  src/pages/PayMoney/PayMoneyPage.styles.tsx
  src/pages/PayMoney/PayMoneyPage.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#174 feat: mainpage css 변경사항
  src/components/MainPage/ListItemComponent/AllProductList.styles.tsx
  src/components/MainPage/MainPage.styles.tsx
  src/components/MainPage/MainPage.tsx
  src/components/MainPage/Swiper/BannerSwiper.styles.tsx
  src/components/common/Footer/DefaultFooter.styles.tsx
  src/components/common/Header/CategoryHeader.tsx
  src/pages/DefaultLayout/DefaultLayout.tsx
Labels: ✨ feature

#176 feat: categorypage, productpage css 변경사항
  src/components/common/Footer/DefaultFooter.styles.tsx
  src/pages/Category/Menu.styles.tsx
  src/pages/Category/Menu.tsx
  src/pages/ProductPage/ProductPage.styles.tsx
Labels: ✨ feature

#177 feat : 마이페이지 유저 정보 및 판매중인 상품 기능 구현
  src/apis/order.ts
  src/apis/point.ts
  src/apis/user.ts
  src/components/common/Header/Header.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/Payment/Payment.tsx
  src/pages/PointHistory/PointHistory.styles.tsx
  src/pages/PointHistory/PointHistory.tsx
  src/pages/SellingProduct/SellingProduct.styles.tsx
  src/pages/SellingProduct/SellingProduct.tsx
  src/pages/routes.tsx
  src/queries/order/query.ts
Labels: ✨ feature

#179 feat : mypage wishList
  src/apis/wish.ts
  src/components/DetailFooter/DetailFooter.tsx
  src/components/Mypage-Wish/WishItems.styles.tsx
  src/components/Mypage-Wish/WishItems.tsx
  src/components/Mypage-Wish/WishPage.styles.tsx
  src/components/Mypage-Wish/WishPage.tsx
  src/components/common/Header/Header.tsx
  src/pages/DetailPage/DetailPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#182 feat : detail page footer 분기 처리
  src/components/DetailFooter/DetailFooter.tsx
Labels: ✨ feature

#183 fix : 상세 페이지에서 heart 유지 X
  src/components/DetailFooter/DetailFooter.tsx
  src/components/Mypage-Wish/WishItems.styles.tsx
  src/components/Mypage-Wish/WishPage.styles.tsx
  src/components/Mypage-Wish/WishPage.tsx
  src/pages/DetailPage/DetailPage.tsx
Labels: 🐛 bug

#188 feat : 카카오 소셜 로그인 구현
  src/apis/user.ts
  src/pages/KakaoCallbackPage/KakaoCallbackPage.tsx
  src/pages/SignInPage/SignInPage.tsx
  src/pages/routes.tsx
Labels: ✨ feature

#190 feat:#189 마이페이지 쿠폰 css 수정완료
  src/pages/Coupon/Coupon.styles.tsx
  src/pages/Coupon/Coupon.tsx
Labels: ✨ feature

#193 feat: search페이지 추가사항 디바운스를 이용한 키워드검색 기능 구현
  src/hooks/useDebounce.ts
  src/pages/Search/Search.tsx
  src/pages/Search/SearchList.styles.tsx
  src/pages/Search/SearchList.tsx
Labels: ✨ feature

#192 fix : 닉네임 중복확인 api url 변경
  src/apis/user.ts
Labels: 🐛 bug

#194 feat : 주문 api 기능 구현 완료
  src/apis/cart.ts
  src/apis/order.ts
  src/components/DetailFooter/DetailFooter.tsx
  src/pages/CartPage/CartPage.tsx
  src/pages/Payment/Payment.tsx
  src/queries/order/query.ts
Labels: ✨ feature

#197 feat : paymoney API 연동
  src/apis/paymoney.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/PayMoney/PayMoneyPage.tsx
Labels: ✨ feature

#199 feat: footer , header 변경사항
  src/assets/icon/Facebook.svg
  src/assets/icon/Instagram.svg
  src/assets/icon/Youtube.svg
  src/assets/icon/index.ts
  src/components/common/Footer/DefaultFooter.styles.tsx
  src/components/common/Footer/DefaultFooter.tsx
  src/components/common/Header/SearchHeader.styles.tsx
  src/components/common/Header/SearchHeader.tsx
  src/styles/theme.ts
Labels: ✨ feature

#200 fix : 상세페이지SELLER footer 해당 SELLER만 보이게 / feat : 로고 클릭 시 메인 페이지로
  src/components/Detail/Detail.styles.tsx
  src/components/DetailFooter/DetailFooter.tsx
  src/components/common/Header/SearchHeader.tsx
  src/pages/DetailPage/DetailPage.tsx
Labels: 🐛 bug, ✨ feature

#201 fix : footer 빠져있던 부분 수정 및 css 수정
  src/components/common/Header/SearchHeader.styles.tsx
  src/pages/SignInPage/SignInPage.styles.tsx
  src/pages/SignInPage/SignInPage.tsx
  src/pages/SignUpPage/SignUpPage.styles.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpUserPage/SignUpUserPage.styles.tsx
  src/pages/SignUpUserPage/SignUpUserPage.tsx
Labels: 🐛 bug

#202 release : 3차 배포를 위한 merge
  src/apis/paymoney.ts
  src/assets/icon/Facebook.svg
  src/assets/icon/Instagram.svg
  src/assets/icon/Youtube.svg
  src/assets/icon/index.ts
  src/components/Detail/Detail.styles.tsx
  src/components/DetailFooter/DetailFooter.tsx
  src/components/common/Footer/DefaultFooter.styles.tsx
  src/components/common/Footer/DefaultFooter.tsx
  src/components/common/Header/SearchHeader.styles.tsx
  src/components/common/Header/SearchHeader.tsx
  src/pages/DetailPage/DetailPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/PayMoney/PayMoneyPage.tsx
  src/pages/SignInPage/SignInPage.styles.tsx
  src/pages/SignInPage/SignInPage.tsx
  src/pages/SignUpPage/SignUpPage.styles.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpUserPage/SignUpUserPage.styles.tsx
  src/pages/SignUpUserPage/SignUpUserPage.tsx
  src/styles/theme.ts
Labels: 🎉 release
