Repository supercoding-commerce/FE, pull requests merged in 2023-12, with the labels that each got.

#229 feat: api 토큰 만료시 로그아웃 기능 구현
  src/apis/index.ts
  src/constants/index.ts
  src/recoil/userState.ts
Labels: ✨ feature

#235 refactor: 무한스크롤부분 2개 컴포넌트 공통으로 처리 및 메인페이지 스크롤부분에 적용
  src/apis/categoryProduct.ts
  src/components/InfiniteScrollList/ScrollProductList.tsx
  src/components/MainPage/MainPage.tsx
  src/pages/ProductPage/CategoryList.tsx
Labels: ✨ feature, ♻️ refactor

#236 refactor:ProductPage 무한스크롤 컴포넌트 적용 및 스크롤컴포넌트 props수정
  src/apis/categoryProduct.ts
  src/components/InfiniteScrollList/ScrollProductList.tsx
  src/pages/ProductPage/CategoryList.tsx
  src/pages/ProductPage/ProductPage.tsx
Labels: ✨ feature, ♻️ refactor

#238 refactor:productpage 무한스크롤 컴포넌트 적용 및 queryKey 추가
  .vscode/settings.json
  src/apis/categoryProduct.ts
  src/pages/ProductPage/CategoryList.tsx
  src/pages/ProductPage/ProductPage.tsx
Labels: ♻️ refactor

#239 refactor: mainpage 무한스크롤 데이터통신 함수에 전달받는 props 수정
  src/apis/product.ts
Labels: 🐛 bug, ✨ feature
