Repository supercoding-commerce/FE, pull requests merged in 2023-10, with the labels that each got.

#205 feat : React Toastify
  package.json
  src/App.tsx
  src/components/DetailFooter/DetailFooter.tsx
  src/components/common/Toastify/Toastify.tsx
  yarn.lock
Labels: ✨ feature

#207 feat : 장바구니 알람+이동 modal
  src/components/DetailFooter/CartModal/CartModal.styles.tsx
  src/components/DetailFooter/CartModal/CartModal.tsx
  src/components/DetailFooter/DetailFooter.tsx
Labels: ✨ feature

#208 refactor:chat 관련 분리 및 수정
  src/components/chat/ChatDetail.tsx
  src/components/chat/chatDetail/ChatDetailBody.tsx
  src/components/chat/chatDetail/ChatDetailHeader.tsx
  src/components/chat/chatDetail/ChatLeaveBox.tsx
  src/hooks/useChat.ts
  src/models/chat.ts
  src/recoil/productListState.ts
Labels: ♻️ refactor

#210 refactor:useChat.tsx 로직 함수로 분리 완료
  src/hooks/useChat.ts
  src/models/chat.ts
Labels: ♻️ refactor

#213 refactor: mainpage 무한스크롤 useinfiniteQuery로변경 및 api로직분리
  src/App.tsx
  src/apis/product.ts
  src/components/MainPage/ListItemComponent/AllProductList.tsx
  src/components/MainPage/ListItemComponent/ListItem.tsx
Labels: ♻️ refactor

#220 리드미 추가
  README.md
Labels: 📝 docs

#218 refactor: chat 관련 로직 분리 및 정리2
  src/apis/chat.ts
  src/components/chat/ChatDetail.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/chatDetail/ChatDetailBody.tsx
  src/components/chat/chatDetail/ChatLeaveBox.tsx
  src/components/chat/chatDetail/ChatSend.tsx
  src/hooks/useChat.ts
  src/hooks/useSendMessage.ts
Labels: ♻️ refactor

#225 refactor: CategoryList 무한스크롤 useInfiniteQuery로 변경
  src/assets/icon/react.svg
  src/pages/ProductPage/CategoryList.tsx
  src/pages/ProductPage/ProductPage.tsx
  yarn.lock
Labels: ♻️ refactor

#222 feat:review 작성 / 불러오기 reactquery로 변경 완료
  src/apis/product.ts
  src/apis/review.ts
  src/components/Detail/detailReview/Review.tsx
  src/components/Detail/detailReview/ReviewBox.tsx
  src/components/Detail/detailReview/ReviewFilterButton.tsx
  src/components/Detail/detailReview/ReviewWrite.tsx
  src/pages/DetailPage/DetailPage.tsx
  src/queries/queryKeys.ts
  src/queries/review/mutation.ts
  src/queries/review/query.ts
Labels: ✨ feature
